create table t_flight_city
(
    airline_code varchar(3) primary key,
    city_code    varchar(3) unique,
    city_name    varchar(50)
);

create table t_flight
(
    id                  int generated by default as identity
        primary key,
    airline_id          int,
    departure_date      timestamp,
    arrival_date        timestamp,
    delay               interval,
    origin_id           varchar(3),
    destination_id      varchar(3),
    base_fare           numeric(10, 2),
    adult_fare          numeric(10, 2),
    status              VARCHAR(50) CHECK (status IN ('ACTIVE', 'DELAYED', 'CANCELED')) DEFAULT 'ACTIVE',
    no_total_places     integer,
    no_available_places integer,
    constraint fk_airline foreign key (airline_id) references t_airline (id),
    constraint fk_origin foreign key (origin_id) references t_flight_city (airline_code),
    constraint fk_destination foreign key (destination_id) references t_flight_city (airline_code)
);