create table t_reservation
(
    id                  int generated by default as identity
        primary key,
    flight_id           int,
    date                timestamp                                                 default CURRENT_TIMESTAMP,
    booking_party_id    int,
    participants_number int                                                       default 1,
    status              VARCHAR(50) CHECK (status IN ('NEW', 'PAID', 'CANCELED')) DEFAULT 'NEW',
    constraint fk_flight foreign key (flight_id) references t_flight (id),
    constraint fk_user foreign key (booking_party_id) references t_user (id)
);

create table t_reservation_participant
(
    id             int generated by default as identity primary key,
    reservation_id int,
    first_name     varchar(50),
    last_name      varchar(50),
    is_adult       boolean default true,
    constraint fk_reservation foreign key (reservation_id) references t_reservation (id)
);

create table t_reservation_log
(
    id             int generated by default as identity primary key,
    log_date       timestamp default current_timestamp,
    reservation_id int,
    status         VARCHAR(50) CHECK (status IN ('NEW', 'PAID', 'CANCELED')),
    constraint fk_reservation foreign key (reservation_id) references t_reservation (id)
);